-- Sync redesigned Safety Library V2 assets
-- Categories: PPE, Tools, Instruments (Mapping "Insulators" to Instruments or a new category if preferred, but user said PPE, Tools, Instruments, Charts, Others)
-- We will map Insulators to a new category "Insulators" if the component supports it, 
-- but looking at SafetyLibrary.jsx, it has: PPE, Tools, Instruments, Charts, Others.
-- I will map "Insulators" folder to "Instruments" or "Tools" based on usage, 
-- but actually let's use the categories provided in the UI.

DO $$
BEGIN

-- PPE CATEGORY
INSERT INTO public.safety_library (item_id, category, name_en, name_bn, function_en, function_bn, images, approx_price_inr, guide_en, guide_bn)
VALUES 
('helmet', 'PPE', 'Safety Helmet', 'সেফটি হেলমেট', 'Protects the head from falling objects and accidental impacts.', 'মাথাকে উপর থেকে পড়া বস্তু এবং আকস্মিক আঘাত থেকে রক্ষা করে।', ARRAY['https://drive.google.com/file/d/1MEIvUDmF_47rVwW7Yd-vcx6hi8UmfUxE/view', 'https://drive.google.com/file/d/1XSlucUsiY24W1DJZveYNS0HlvVinXKwx/view', 'https://drive.google.com/file/d/1R4IDx9DmEpBkjx9uMweVSJv-jMQz9TiS/view', 'https://drive.google.com/file/d/1yjeNC2T-pVJ-EdnFLOel2xVojfl9Es9x/view', 'https://drive.google.com/file/d/1JEA3245guZz197ku16oILrDp9t_OoiOt/view'], 450, 'Always wear with the chin strap fastened. Inspect for cracks before use.', 'সবসময় চিন স্ট্র্যাপ লাগিয়ে ব্যবহার করুন। ব্যবহারের আগে পরীক্ষা করুন।'),
('gloves', 'PPE', 'Insulated Gloves', 'ইনসুলেটেড গ্লাভস', 'Provides electrical insulation when working on live lines.', 'লাইভ লাইনে কাজ করার সময় বৈদ্যুতিক নিরোধক সরবরাহ করে।', ARRAY['https://drive.google.com/file/d/117JetFwXtpyL9Omm1Cbjoqebq3lqsVXp/view', 'https://drive.google.com/file/d/1eRf32_QtMhypm0Sbw-jOiaKySE22n-Yt/view', 'https://drive.google.com/file/d/1CKfnvhgb_Byw5N1mIOotwt45w49fp5G_/view', 'https://drive.google.com/file/d/1_8KCUgZScL3CrksEm5gnHxi-R4TgQuGf/view', 'https://drive.google.com/file/d/1DSp4_c-JqkpMxs6rF4IxbDHA-hB4wz2G/view'], 3200, 'Perform air-leak test before every use. Use with leather protectors.', 'প্রতিবার ব্যবহারের আগে এয়ার-লিক টেস্ট করুন। চামড়ার প্রোটেক্টর সহ ব্যবহার করুন।'),
('harness', 'PPE', 'Safety Harness', 'সেফটি হারনেস', 'Prevents falls from heights during pole or tower work.', 'পোল বা টাওয়ারে কাজ করার সময় উচ্চতা থেকে পড়ে যাওয়া রোধ করে।', ARRAY['https://drive.google.com/file/d/1u87lNqM6TO_oo0saHFSiatapq4m6AgG4/view', 'https://drive.google.com/file/d/1EkmTgYhtXmb_nchPs3NzBB4CycUXQ201/view', 'https://drive.google.com/file/d/1JGqS3bVfFO4Yo2li8pjLMHHEy4yhRjjo/view', 'https://drive.google.com/file/d/1pVfBhsjoA00-gXQiaURTAWXgIK3qxEQQ/view', 'https://drive.google.com/file/d/1huSa4pQdKiiWPLbk9SKxTSxfhrtHsnaj/view'], 2400, 'Ensure all buckles are tight. Anchoring point must be above shoulder level.', 'সবগুলো বাকল শক্তভাবে আটকানো নিশ্চিত করুন। কাঁধের উপরে অ্যাঙ্কর করুন।'),
('boots', 'PPE', 'Safety Boots', 'সেফটি বুট', 'Slip-resistant and electrically insulated footwear for site safety.', 'সাইট সুরক্ষার জন্য পিচ্ছিল-রোধী এবং বৈদ্যুতিকভাবে নিরোধক জুতো।', ARRAY['https://drive.google.com/file/d/1t6F4BMf_aQc2PuWbQxZ_3wxCGOjhU0lD/view', 'https://drive.google.com/file/d/1hpWNElbr6IIu8FGh1EaLymqlRZFPAwR5/view', 'https://drive.google.com/file/d/14W1HZAb6ap3W1CDaH4sXD4x00zeSB7hh/view', 'https://drive.google.com/file/d/1RIYatL0PRJW48QseeGkzCh47-bN64qBI/view', 'https://drive.google.com/file/d/1Fq9ytkY6-IXiKJQACstwdzVC3wKJoYVr/view'], 1800, 'Keep dry for maximum electrical safety. Clean soles regularly.', 'বৈদ্যুতিক নিরাপত্তার জন্য শুকনো রাখুন। সোলে কাদা জমলে পরিষ্কার করুন।'),
('gumboot', 'PPE', 'Gumboot', 'গামবুট', 'Waterproof footwear for wet terrain and sludge.', 'ভেজা এবং কাদাযুক্ত জায়গায় কাজ করার জন্য জলরোধী জুতো।', ARRAY['https://drive.google.com/file/d/1kYk9X4S2ZacobJTMu5sfQ7CirBSb14_U/view', 'https://drive.google.com/file/d/1BmSeSF1hHAfslEbcpKRB5dOTO1-6O1R7/view', 'https://drive.google.com/file/d/1-QUY1CSR-wpnusP4ScMhMsm10opqtc4E/view'], 800, 'Check for punctures. Clean after use in chemical environments.', 'ছিদ্র আছে কিনা পরীক্ষা করুন। ব্যবহারের পর ভালো করে পরিষ্কার করুন।'),
('vest', 'PPE', 'High Visibility Vest', 'সেফটি ভেস্ট', 'Highly reflective vest for site visibility.', 'সাইট সুরক্ষার জন্য উচ্চ রিফ্লেক্টিভ ভেস্ট।', ARRAY['https://drive.google.com/file/d/1O-T3_eb0i4kI_js9ydNPhATC2E2IBdiF/view', 'https://drive.google.com/file/d/1k2sP5lF_jWm5oBp9Lfk9XZ3b_lfOzdHd/view', 'https://drive.google.com/file/d/1i67N2RXct3nnRP7sxFWJjb0VRxs_MDg-/view'], 350, 'Keep reflective strips clean.', 'রিফ্লেক্টিভ স্ট্রিপগুলো পরিষ্কার রাখুন।'),
('arc_vest', 'PPE', 'Arc/Fire Resistant Vest', 'আর্ক/ফায়ার রেজিস্ট্যান্ট ভেস্ট', 'Protects against electrical arc flashes and heat.', 'বৈদ্যুতিক আর্ক ফ্লাশ এবং তাপ থেকে রক্ষা করে।', ARRAY['https://drive.google.com/file/d/118dsL4WFsGJa7jBM8Q36UmJrYTXq15EC/view', 'https://drive.google.com/file/d/1p1Ay02CK0371uEDtYjbGRFmdNkHC3jd_/view', 'https://drive.google.com/file/d/14oUDwYP6mvNVDEJIx7_BiuMXVAz2_J4i/view'], 4500, 'Inspect for tears or degradation of fire-retardant material.', 'আগুনে পোড়া বা ছিঁড়ে যাওয়া অংশ আছে কিনা দেখে নিন।'),
('ladder', 'PPE', 'Industrial Ladder', 'ইন্ডাস্ট্রিয়াল ল্যাডার', 'Access tools for climbing poles and structures.', 'পোল এবং টাওয়ার এ ওঠার জন্য ব্যবহৃত সরঞ্জাম।', ARRAY['https://drive.google.com/file/d/1eckJbgRfHg8Nw9UrNz0DO23dIff884c5/view', 'https://drive.google.com/file/d/1Ruq34kQ_cbTW7ENVmv2_quUGo8R8QvX4/view', 'https://drive.google.com/file/d/1SXtHws3ND9krBwltGAA_s69McXQ4JYx6/view', 'https://drive.google.com/file/d/1uWjj1o5eMSxho6uw4eiJe2-KSmHhIwS7/view'], 5500, 'Ensure firm footing and stable angle before climbing.', 'ওঠার আগে শক্ত ভূমি এবং সঠিক কোণ নিশ্চিত করুন।'),
('shorting_chain', 'PPE', 'Shorting Chain', 'শর্টিং চেইন', 'Grounds power lines after disconnection for safety.', 'নিরাপত্তার জন্য সংযোগ বিচ্ছিন্ন করে গ্রাউন্ডিং করতে ব্যবহৃত হয়।', ARRAY['https://drive.google.com/file/d/1GoQTUAOjGWQPcrVT_0vZdsAMuDSPfHqV/view', 'https://drive.google.com/file/d/1MkjOtEjYZiU9g0gDn5QGLE0HpJBwGJ4K/view', 'https://drive.google.com/file/d/1YULpo7Er8aAZefEgpiKUt9K91g2REMG6/view', 'https://drive.google.com/file/d/1H8417IHN-4Bgrv-uldSDNoYL2hD5rxkO/view'], 1500, 'Ensure solid contact with earth and line.', 'মাটি এবং লাইনের সাথে শক্ত সংযোগ নিশ্চিত করুন।'),
('lanyard', 'PPE', 'Safety Lanyard & Hook', 'ল্যানিয়ার্ড এবং হুক', 'Connecting element for fall arrest systems.', 'পতন রোধ ব্যবস্থার জন্য সংযোগকারী সরঞ্জাম।', ARRAY['https://drive.google.com/file/d/15RArX4g6JBB1lqPZAT9HQ7SmtKTNXj_n/view', 'https://drive.google.com/file/d/1B0dGKUEppsmobdOWHCsKhwMYUXTFIL1K/view', 'https://drive.google.com/file/d/1fviLskSzWZM3JpKxV9OIp-rSKrS9_0FU/view', 'https://drive.google.com/file/d/1dLVcOVZixGNyRa1srYUw731AtFKNkT0T/view', 'https://drive.google.com/file/d/1rvnq6MBLT9GJuo2H3MI62JDnxbZSbE4p/view', 'https://drive.google.com/file/d/16hIFr4J9DYtqdBUw5uepf2XUriqk25Xc/view'], 1200, 'Check hook mechanism for smooth operation.', 'হুক ঠিকমতো কাজ করছে কিনা দেখে নিন।'),
('goggles', 'PPE', 'Safety Goggles', 'সেফটি চশমা', 'Protects eyes from dust, sparks, and impacts.', 'ধুলাবালি এবং স্ফুলিঙ্গ থেকে চোখ রক্ষা করে।', ARRAY['https://drive.google.com/file/d/15N4LjbykEoZjrPrKnCHLJznmfu7yaoQj/view', 'https://drive.google.com/file/d/1NXpYep-YD4uDGJQnHf9SZatTbxHkFHVS/view'], 250, 'Ensure clear visibility. Replace if heavily scratched.', 'পরিষ্কার দৃষ্টি নিশ্চিত করুন। অতিরিক্ত দাগ হলে বদলে ফেলুন।'),
('torch', 'PPE', 'Helmet Mounted Torch', 'হেলমেট টর্চ', 'Hands-free lighting for night work.', 'রাতে কাজের জন্য হ্যান্ডস-ফ্রি আলো।', ARRAY['https://drive.google.com/file/d/1UDW3wQNHeG0OJjhxXpf6ybSzvo6QW091/view', 'https://drive.google.com/file/d/1a-ahZlHHctL1keEfUBzNqXOAj3FOVowx/view'], 850, 'Maintain charged batteries/cells.', 'ব্যাটারি চার্জ আছে কিনা নিশ্চিত করুন।'),
('rope', 'PPE', 'Manila Rope', 'ম্যানিলা রোপ', 'High-strength rope for lifting and securing.', 'ভারী মালামাল তোলা এবং বাঁধার জন্য উচ্চ-শক্তির দড়ি।', ARRAY['https://drive.google.com/file/d/1MdxK7-wA3FrRWuIMnth9eXmeo0GDoc34/view', 'https://drive.google.com/file/d/1Yzvpy8jo8TqylnwuEuLcwavHVlEtLsOp/view'], 1200, 'Inspect for fraying or rotting.', 'ছিঁড়ে যাওয়া বা পচন ধরা আছে কিনা পরীক্ষা করুন।'),

-- INSTRUMENTS / INSULATORS (User provided as Insulators folder, mapping to Instruments or Tools)
-- We will use category 'Instruments' for high-precision testing tools
('tester', 'Instruments', 'Insulation Tester', 'ইনসুলেশন টেস্টার', 'Measures electrical resistance of insulators (Megger).', 'ইনসুলেটরের বৈদ্যুতিক প্রতিরোধ পরিমাপ করে (মেগার)।', ARRAY['https://drive.google.com/file/d/1cr44PHeK4AbBjlH36km3Dkn6c8t_OFhN/view', 'https://drive.google.com/file/d/1VtrIp2IQ9mkXF10R-lxnJhWMnNR1GUtf/view', 'https://drive.google.com/file/d/1CTjmkk0mtVOn8cHKLWjfJgahdJx19d6h/view', 'https://drive.google.com/file/d/1Jpyk-yVcYBsJyauoD5LV6enaRXoLiy-M/view', 'https://drive.google.com/file/d/1e_jdFvFdDvPsTQA5JE96GgVZHNCsAb5r/view'], 15000, 'Calibrate annually. Discharge cables before and after testing.', 'প্রতি বছর ক্যালিব্রেট করুন। পরীক্ষার আগে-পরে কেবল ডিসচার্জ করুন।'),
('multimeter', 'Instruments', 'Digital Multimeter', 'ডিজিটাল মাল্টিমিটার', 'Measures voltage, current, and resistance.', 'ভোল্টেজ, কারেন্ট এবং রেজিস্ট্যান্স পরিমাপ করে।', ARRAY['https://drive.google.com/file/d/1hJXuP7AJE3vPaN-BYzL3K2Cu1HY9gcEo/view', 'https://drive.google.com/file/d/1gBDWJE31Kg9NpT1zwDwlA0_8kOrvT14d/view', 'https://drive.google.com/file/d/1vVKjcqas7k9ZfDWR6l_mp3LFDsXWjQj1/view'], 4500, 'Use correct range settings to prevent damage.', 'সঠিক রেঞ্জ ব্যবহার করুন।'),
('clamp_meter', 'Instruments', 'Clamp-on Meter', 'ক্ল্যাম্প মিটার', 'Measures current without breaking the circuit.', 'সার্কিট বিচ্ছিন্ন না করেই কারেন্ট পরিমাপ করে।', ARRAY['https://drive.google.com/file/d/173t_yLlpdtnSWTjum5Rq7cfMIg-ISEb5/view', 'https://drive.google.com/file/d/1UMsG2NmcR9WdHhifKufaP16xA5LMLByi/view', 'https://drive.google.com/file/d/1qFyRsDiK_0-C2n_J_j0tLJESomvvHzOG/view'], 5500, 'Ensure clamp jaws are fully closed for accuracy.', 'সঠিক পাফের জন্য জ’ গুলো পুরোপুরি বন্ধ করুন।'),
('voltage_tester', 'Instruments', 'Voltage Detector', 'ভোল্টেজ টেস্টার', 'Detects presence of voltage in lines.', 'লাইনে ভোল্টেজের উপস্থিতি শনাক্ত করে।', ARRAY['https://drive.google.com/file/d/1XAgwyx6TEZPoIDWNuaMqakgRGPCRcXwz/view', 'https://drive.google.com/file/d/1HgVwnWhlJjZFL9jH7-MOxBOffe_G9bsu/view', 'https://drive.google.com/file/d/1-uxdqr7I2qB2-Z8GZbKy0ktmKX8pYvFz/view', 'https://drive.google.com/file/d/17Gf3w8s5OvNq-eKTYCPlPQfekWom3okW/view', 'https://drive.google.com/file/d/1Rt8NQINl6aWAYnI5s1HRCGwxIqfjA0r6/view'], 1200, 'Always test on a known live source first.', 'সোর্স দিয়ে পরীক্ষা করে নিন।'),
('imager', 'Instruments', 'Thermal Imager', 'থার্মাল ইমেজার', 'Identifies hotspots in electrical connections.', 'সংযোগের হটস্পট বা উচ্চ তাপ শনাক্ত করে।', ARRAY['https://drive.google.com/file/d/1DKP7lZL3xRwSjEsr7gRlv_WKTpVcBnCo/view', 'https://drive.google.com/file/d/1UbxNmPiLB9RqIZ8uSHJn3HsnfkUOMH_L/view', 'https://drive.google.com/file/d/10H8lbdvR-x_6_paqGsTY8G2XTvI8fO3v/view', 'https://drive.google.com/file/d/1hEsRhC7QaLT_GA8g9buJ1I9QG1vDT0cM/view', 'https://drive.google.com/file/d/1cRZvWv_XkBcQr28jaX7Ez0lkpisxuI7O/view'], 85000, 'Wipe lens only with soft microfiber cloth.', 'সফট মাইক্রোফাইবার কাপড় দিয়ে লেন্স মুছুন।'),
('earth_tester', 'Instruments', 'Earth Resistance Tester', 'আর্থ টেস্টার', 'Measures grounding system efficiency.', 'গ্রাউন্ডিং সিস্টেমের কার্যকারিতা পরিমাপ করে।', ARRAY['https://drive.google.com/file/d/1zPMZuS_bWNCeTcrL4pizwLlOpMsyKhLU/view', 'https://drive.google.com/file/d/1MhxPrh3ecSe1U90ftAPwAzjnEN39uYjE/view'], 8500, 'Ensure spikes are firmly driven into soil.', 'স্পাইকগুলো মাটিতে শক্তভাবে গেঁথে নিন।'),

-- INSULATORS (Mapping to Others or Instruments as reference)
('insulator_pin', 'Others', 'Pin Insulator', 'পিন ইনসুলেটর', 'Supports power lines on crossarms.', 'ক্রসআর্মে লাইনের ভার বহনে সাহায্য করে।', ARRAY['https://drive.google.com/file/d/1oLGvxOapjPqZgUpHC0mi3uBHfoQw4lN2/view', 'https://drive.google.com/file/d/12B7OJiR5Mx4j687AgVIyg0-o3KGdkX_e/view', 'https://drive.google.com/file/d/1NYJY9suOCI3JY0gfYecOMOGZYBKL6yhR/view', 'https://drive.google.com/file/d/1ecQeNeXryomfE-QZloYErap-phLIdhTh/view'], NULL, 'Used for low to medium voltage distribution.', 'নিম্ন ও মাঝারি ভোল্টেজ ডিস্ট্রিবিউশনে ব্যবহৃত হয়।'),
('insulator_disc', 'Others', 'Disc Insulator', 'ডিস্ক ইনসুলেটর', 'Provides insulation for high-voltage strain/suspension.', 'উচ্চ-ভোল্টেজের স্টেইন বা সাসপেনশন ইনসুলেশন প্রদান করে।', ARRAY['https://drive.google.com/file/d/1G0hYQMB31l-Xir3j2gMhe-xIjzhN5ijI/view', 'https://drive.google.com/file/d/1kBkCUJU7sUdxqBmu2GKoi5HqCk11fTyN/view', 'https://drive.google.com/file/d/1J5-XqhD9DBmGNaZQDKIy2AOOXqhEpke6/view', 'https://drive.google.com/file/d/1Wxj-i8uCSKyQvJA3jtPorHy82MWAgUTY/view', 'https://drive.google.com/file/d/1ajeUeQAyIohICBN7_5fv2kIEU0Nps-b7/view'], NULL, 'Inspect for glazing chips or surface cracks.', 'মাটির আবরণের কোনো অংশ উঠে গেছে কিনা বা ফাটল আছে কিনা দেখুন।'),
('insulator_guy', 'Others', 'Guy/Stay Insulator', 'গাই ইনসুলেটর', 'Insulates the stay wire from the pole.', 'পোল থেকে গাই বা স্টে ওয়্যারকে আলাদা করে।', ARRAY['https://drive.google.com/file/d/1JE62cwo1TG9hYqkEnZrc7DSHkbRDkzRB/view', 'https://drive.google.com/file/d/13rktahOy4cppfYAfHFfeGlNM4sT1Cb1z/view'], NULL, 'Install at a safe height above ground.', 'ভূমি থেকে নিরাপদ উচ্চতায় স্থাপন করুন।'),
('insulator_shackle', 'Others', 'Shackle Insulator', 'শ্যাকেল ইনসুলেটর', 'Used at dead-ends of distribution lines.', 'ডিস্ট্রিবিউশন লাইনের টার্মিনেশনে ব্যবহৃত হয়।', ARRAY['https://drive.google.com/file/d/1922EQ6pIKSKY4wlyTGhJeziZ3DT_NPIL/view', 'https://drive.google.com/file/d/1nNeLq0f-J_5AMZp8iq_mpchRvaIWrmuZ/view'], NULL, 'Check for proper fitting with strap/clamp.', 'স্ট্র্যাপ বা ক্ল্যাম্পের সাথে সঠিক ফিটিং দেখে নিন।'),
('insulator_reel', 'Others', 'Reel Insulator', 'রিল ইনসুলেটর', 'Used for secondary distribution lines.', 'সেকেন্ডারি ডিস্ট্রিবিউশন লাইনে ব্যবহৃত হয়।', ARRAY['https://drive.google.com/file/d/1HfxYMLQSoAz-OXsIZcrEhzDhIMw5T8tG/view', 'https://drive.google.com/file/d/1DSpdtOLGF3WUzSmcOzkUoSc7EuD7IAeu/view'], NULL, 'Ensure smooth rope/wire passage.', 'তারের অবাধ চলাফেরা নিশ্চিত করুন।')

ON CONFLICT (item_id) DO UPDATE SET
    category = EXCLUDED.category,
    name_en = EXCLUDED.name_en,
    name_bn = EXCLUDED.name_bn,
    function_en = EXCLUDED.function_en,
    function_bn = EXCLUDED.function_bn,
    images = EXCLUDED.images,
    approx_price_inr = COALESCE(EXCLUDED.approx_price_inr, safety_library.approx_price_inr),
    guide_en = COALESCE(EXCLUDED.guide_en, safety_library.guide_en),
    guide_bn = COALESCE(EXCLUDED.guide_bn, safety_library.guide_bn),
    updated_at = now();

END $$;
